<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { readOntologyModel, saveOntologyModel, type KnowledgeBasePayload, type OntologyEntityTypeDefinition, type OntologyModelInspectionPayload, type OntologyRelationTypeDefinition } from "../../services/api";
import { useNotify } from "../../app/notify";

const props = defineProps<{ knowledgeBase: KnowledgeBasePayload }>();
const notify = useNotify();
const data = ref<OntologyModelInspectionPayload | null>(null), busy = ref(false), saving = ref(false), section = ref<"map"|"entities"|"relations">("map");
const editingEntity = ref<OntologyEntityTypeDefinition | null>(null), editingRelation = ref<OntologyRelationTypeDefinition | null>(null);
const typeNames = computed(() => data.value?.model.entityTypes.map((item) => item.name) || []);
const qualityTone = computed(() => (data.value?.validation.blockers.length ? "rose" : data.value?.validation.warnings.length ? "amber" : "emerald"));
const typeLabels: Record<string,string> = { role:"角色",agent:"智能体",protocol:"协议",concept:"业务概念",product:"产品",metric:"指标",indicator:"指标",person:"人员",organization:"组织",project:"项目",process:"流程",system:"系统",document:"文档",tool:"工具",event:"事件" };
const relationLabels: Record<string,string> = { contributes_to:"参与贡献",enables:"支持实现",evolves_through:"通过其演进",belongs_to:"属于",depends_on:"依赖",uses:"使用",contains:"包含",related_to:"相关",responsible_for:"负责" };
function readable(value:string, dictionary:Record<string,string>){const key=value.trim().toLocaleLowerCase();return dictionary[key]||value.replace(/[_-]+/g," ")}
function typeLabel(value:string){return readable(value,typeLabels)}
function relationLabel(value:string){return readable(value,relationLabels)}
function entityUsage(name:string){return data.value?.usage.entityTypes.find((item)=>item.name===name)||{name,count:0,examples:[]}}
function relationUsage(name:string){return data.value?.usage.relationTypes.find((item)=>item.name===name)||{name,count:0,examples:[]}}
const modelSummary = computed(()=>({entities:data.value?.model.entityTypes.length||0,relations:data.value?.model.relationTypes.length||0,facts:data.value?.usage.relationTypes.reduce((sum,item)=>sum+item.count,0)||0}));
function id(value:string){return value.trim().replace(/\s+/g,"_").replace(/[^\p{L}\p{N}_-]/gu,"").slice(0,120)||`type_${Date.now()}`}
async function load(){busy.value=true;try{data.value=await readOntologyModel(props.knowledgeBase)}catch(error){notify.error(error,"notify.saveFailed")}finally{busy.value=false}}
async function save(){if(!data.value)return;saving.value=true;try{data.value.model=(await saveOntologyModel(props.knowledgeBase,data.value.model)).model;data.value.inferred=false;notify.pushRaw("success","模型规则已保存","后续 AI 分析会自动优先使用这些类型与关系。");await load()}catch(error){notify.error(error,"notify.saveFailed")}finally{saving.value=false}}
function addEntity(){editingEntity.value={id:`type_${Date.now()}`,name:"新实体类型",description:"",color:"#4f6be8",allowAiCreate:true,properties:[]}}
function addRelation(){editingRelation.value={id:`relation_${Date.now()}`,name:"新关系",description:"",subjectTypes:[],objectTypes:[],allowAiCreate:true}}
function editEntity(item:OntologyEntityTypeDefinition){editingEntity.value=structuredClone(item)}
function editRelation(item:OntologyRelationTypeDefinition){editingRelation.value=structuredClone(item)}
function saveEntity(){if(!data.value||!editingEntity.value?.name.trim())return;editingEntity.value.id=editingEntity.value.id||id(editingEntity.value.name);const index=data.value.model.entityTypes.findIndex((item)=>item.id===editingEntity.value?.id);if(index>=0)data.value.model.entityTypes[index]=editingEntity.value;else data.value.model.entityTypes.push(editingEntity.value);editingEntity.value=null;void save()}
function saveRelation(){if(!data.value||!editingRelation.value?.name.trim())return;editingRelation.value.id=editingRelation.value.id||id(editingRelation.value.name);const index=data.value.model.relationTypes.findIndex((item)=>item.id===editingRelation.value?.id);if(index>=0)data.value.model.relationTypes[index]=editingRelation.value;else data.value.model.relationTypes.push(editingRelation.value);editingRelation.value=null;void save()}
function addProperty(){editingEntity.value?.properties.push({id:`property_${Date.now()}`,name:"新属性",dataType:"text",required:false})}
function toggleType(list:string[],value:string){const index=list.indexOf(value);index>=0?list.splice(index,1):list.push(value)}
watch(()=>props.knowledgeBase.id,load);onMounted(load);
</script>

<template>
  <section class="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]">
    <header class="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--border)] px-5 py-4">
      <div><div class="flex items-center gap-2"><h3 class="font-semibold">业务知识规则</h3><span :class="['rounded-md px-2 py-1 text-[10px] font-semibold',data?.inferred?'bg-blue-50 text-blue-700':'bg-emerald-50 text-emerald-700']">{{ data?.inferred?'AI 自动归纳 · 待确认':'已确认并生效' }}</span></div><p class="mt-1 text-xs text-[var(--muted)]">这里定义“哪些业务对象可以通过什么关系连接”，不是具体业务事实。</p></div>
      <div class="flex items-center gap-2"><span :class="['rounded-md px-3 py-1.5 text-xs font-semibold',qualityTone==='rose'?'bg-rose-100 text-rose-700':qualityTone==='amber'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700']">{{ data?.validation.blockers.length||data?.validation.warnings.length ? `${(data?.validation.blockers.length||0)+(data?.validation.warnings.length||0)} 项需确认` : '规则检查通过' }}</span><button class="rounded-lg bg-[var(--accent)] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50" :disabled="saving||!data" @click="save">{{ saving?'保存中…':data?.inferred?'确认并用于后续 AI':'保存规则调整' }}</button></div>
    </header>
    <div class="grid gap-3 border-b border-blue-200 bg-blue-50/70 px-5 py-4 md:grid-cols-[1fr_auto] md:items-center"><div><strong class="text-sm text-blue-900">关系图谱记录事实，本体规则约束结构</strong><p class="mt-1 text-xs leading-5 text-blue-800">例如“客服专员负责退款流程”是一条事实；“角色可以负责流程”是一条规则。确认后系统会用这些规则指导 AI 抽取、质量检查和召回扩展。</p></div><div class="grid grid-cols-3 gap-2 text-center text-xs"><div class="rounded-lg bg-white/80 px-3 py-2"><strong class="block text-base text-blue-900">{{ modelSummary.entities }}</strong>对象类型</div><div class="rounded-lg bg-white/80 px-3 py-2"><strong class="block text-base text-blue-900">{{ modelSummary.relations }}</strong>关系规则</div><div class="rounded-lg bg-white/80 px-3 py-2"><strong class="block text-base text-blue-900">{{ modelSummary.facts }}</strong>事实依据</div></div></div>
    <div class="flex gap-1 border-b border-[var(--border)] px-5 py-3 text-xs font-semibold"><button v-for="item in [{id:'map',name:'业务规则概览'},{id:'entities',name:'业务对象类型'},{id:'relations',name:'关系词典'}]" :key="item.id" class="rounded-lg px-3 py-2" :class="section===item.id?'bg-[var(--accent)] text-white':'text-[var(--muted)] hover:bg-[var(--surface-muted)]'" @click="section=item.id as typeof section">{{ item.name }}</button></div>
    <div v-if="busy" class="p-16 text-center text-sm text-[var(--muted)]">正在归纳知识模型…</div>
    <div v-else-if="data" class="p-5">
      <div v-if="section==='map'" class="grid gap-3"><div v-if="!data.model.relationTypes.length" class="rounded-xl border border-dashed p-12 text-center text-sm text-[var(--muted)]">当前还没有可归纳的业务关系。完成 AI 构建或新增关系后，系统会在这里生成易读规则。</div><article v-for="relation in data.model.relationTypes" :key="relation.id" class="rounded-xl border border-[var(--border)] p-4"><div class="grid items-center gap-3 md:grid-cols-[1fr_auto_1fr]"><div class="flex flex-wrap justify-end gap-2"><span v-for="type in relation.subjectTypes" :key="type" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">{{ typeLabel(type) }}</span><span v-if="!relation.subjectTypes.length" class="text-xs text-[var(--muted)]">任意业务对象</span></div><button class="rounded-lg border border-[var(--accent)]/30 bg-[var(--accent)]/10 px-4 py-2 text-xs font-semibold text-[var(--accent)]" @click="editRelation(relation)">— {{ relationLabel(relation.name) }} →</button><div class="flex flex-wrap gap-2"><span v-for="type in relation.objectTypes" :key="type" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">{{ typeLabel(type) }}</span><span v-if="!relation.objectTypes.length" class="text-xs text-[var(--muted)]">任意业务对象</span></div></div><div class="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-[var(--border)] pt-3 text-[11px] text-[var(--muted)]"><div><span class="font-semibold text-[var(--text)]">{{ relationUsage(relation.name).count }} 条事实支持</span><span v-if="relationUsage(relation.name).examples.length"> · 例如：{{ relationUsage(relation.name).examples.map(item=>`${item.subject} → ${item.object}`).join('；') }}</span></div><div class="flex items-center gap-2"><span>{{ relation.allowAiCreate?'允许 AI 按此规则识别':'仅人工维护' }}</span><span v-if="relationLabel(relation.name)!==relation.name" class="rounded bg-[var(--surface-muted)] px-2 py-1 font-mono text-[10px]">技术标识 {{ relation.name }}</span><button class="font-semibold text-[var(--accent)]" @click="editRelation(relation)">调整规则</button></div></div></article></div>
      <div v-else-if="section==='entities'"><div class="mb-4 flex justify-between"><p class="text-xs text-[var(--muted)]">业务对象类型帮助 AI 判断“这是什么”，属性规则会在质量检查时自动验证。</p><button class="rounded-lg border px-3 py-2 text-xs font-semibold" @click="addEntity">＋ 新增对象类型</button></div><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><button v-for="entity in data.model.entityTypes" :key="entity.id" class="rounded-xl border border-[var(--border)] p-4 text-left transition hover:border-[var(--accent)]" @click="editEntity(entity)"><div class="flex items-center gap-2"><i class="h-3 w-3 rounded-full" :style="{backgroundColor:entity.color}"/><strong>{{ typeLabel(entity.name) }}</strong><span class="ml-auto text-[10px] text-[var(--muted)]">{{ entityUsage(entity.name).count }} 个实例</span></div><p v-if="typeLabel(entity.name)!==entity.name" class="mt-1 font-mono text-[10px] text-[var(--muted)]">技术标识 {{ entity.name }}</p><p class="mt-2 line-clamp-2 text-xs text-[var(--muted)]">{{ entityUsage(entity.name).examples.length?`例如：${entityUsage(entity.name).examples.join('、')}`:entity.description||'尚无业务实例' }}</p><div class="mt-3 flex flex-wrap gap-1"><span v-for="property in entity.properties.slice(0,4)" :key="property.id" class="rounded bg-[var(--surface-muted)] px-2 py-1 text-[10px]">{{ property.name }}<b v-if="property.required" class="text-rose-600"> *</b></span><span v-if="!entity.properties.length" class="text-[10px] text-[var(--muted)]">暂无必需属性</span></div></button></div></div>
      <div v-else><div class="mb-4 flex justify-between"><p class="text-xs text-[var(--muted)]">关系词典统一业务表达，并规定关系允许连接的对象类型和方向。</p><button class="rounded-lg border px-3 py-2 text-xs font-semibold" @click="addRelation">＋ 新增关系规则</button></div><div class="divide-y divide-[var(--border)]"><button v-for="relation in data.model.relationTypes" :key="relation.id" class="flex w-full items-center gap-4 py-4 text-left" @click="editRelation(relation)"><span class="min-w-32"><strong class="block text-sm">{{ relationLabel(relation.name) }}</strong><small v-if="relationLabel(relation.name)!==relation.name" class="font-mono text-[10px] text-[var(--muted)]">{{ relation.name }}</small></span><span class="text-xs text-[var(--muted)]">{{ relation.subjectTypes.map(typeLabel).join(' / ')||'任意对象' }} → {{ relation.objectTypes.map(typeLabel).join(' / ')||'任意对象' }}</span><span class="ml-auto text-xs text-[var(--muted)]">{{ relationUsage(relation.name).count }} 条事实</span><span class="text-xs font-semibold text-[var(--accent)]">编辑</span></button></div></div>
    </div>
    <div v-if="data&&(data.validation.blockers.length||data.validation.warnings.length)" class="border-t border-[var(--border)] p-5"><h4 class="text-sm font-semibold">需要确认的规则问题</h4><ul class="mt-3 space-y-2 text-xs"><li v-for="item in data.validation.blockers" :key="item" class="rounded-lg bg-rose-50 px-3 py-2 text-rose-700">{{ item }}</li><li v-for="item in data.validation.warnings" :key="item" class="rounded-lg bg-amber-50 px-3 py-2 text-amber-800">{{ item }}</li></ul></div>
  </section>

  <div v-if="editingEntity" class="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div class="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-[var(--surface)] p-5"><div class="flex justify-between"><div><h3 class="font-semibold">实体类型</h3><p class="mt-1 text-xs text-[var(--muted)]">保持简单即可，属性规则由系统提供默认建议。</p></div><button class="text-xs text-[var(--muted)]" @click="editingEntity=null">关闭</button></div><div class="mt-4 grid gap-3 sm:grid-cols-[1fr_120px]"><label class="text-xs font-semibold">类型名称<input v-model="editingEntity.name" class="mt-1 w-full rounded-lg border p-2 font-normal"/></label><label class="text-xs font-semibold">识别颜色<input v-model="editingEntity.color" type="color" class="mt-1 h-10 w-full rounded-lg border p-1"/></label></div><label class="mt-3 block text-xs font-semibold">用途说明<textarea v-model="editingEntity.description" class="mt-1 h-16 w-full rounded-lg border p-2 font-normal"/></label><div class="mt-5 flex items-center justify-between"><strong class="text-sm">属性</strong><button class="rounded-lg border px-3 py-1.5 text-xs" @click="addProperty">＋ 添加属性</button></div><div class="mt-2 space-y-2"><div v-for="(property,index) in editingEntity.properties" :key="property.id" class="grid gap-2 rounded-xl bg-[var(--surface-muted)] p-3 sm:grid-cols-[1fr_120px_auto_auto]"><input v-model="property.name" class="rounded-lg border p-2 text-xs" aria-label="属性名称"/><select v-model="property.dataType" class="rounded-lg border p-2 text-xs" aria-label="数据类型"><option value="text">文本</option><option value="number">数字</option><option value="date">日期</option><option value="boolean">是/否</option></select><label class="flex items-center gap-1 text-xs"><input v-model="property.required" type="checkbox"/> 必填</label><button class="text-xs text-rose-600" @click="editingEntity.properties.splice(index,1)">删除</button></div></div><label class="mt-4 flex items-center gap-2 text-xs"><input v-model="editingEntity.allowAiCreate" type="checkbox"/>允许 AI 自动识别此类型</label><div class="mt-5 flex justify-end gap-2"><button class="rounded-lg border px-3 py-2 text-sm" @click="editingEntity=null">取消</button><button class="rounded-lg bg-[var(--accent)] px-4 py-2 text-sm text-white" @click="saveEntity">保存</button></div></div></div>
  <div v-if="editingRelation" class="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><div class="w-full max-w-2xl rounded-2xl bg-[var(--surface)] p-5"><div class="flex justify-between"><div><h3 class="font-semibold">关系规则</h3><p class="mt-1 text-xs text-[var(--muted)]">选择允许连接的实体类型，其余校验由系统自动完成。</p></div><button class="text-xs text-[var(--muted)]" @click="editingRelation=null">关闭</button></div><label class="mt-4 block text-xs font-semibold">关系名称<input v-model="editingRelation.name" class="mt-1 w-full rounded-lg border p-2 font-normal"/></label><div class="mt-4 grid gap-4 sm:grid-cols-2"><div><strong class="text-xs">从哪些类型出发</strong><div class="mt-2 flex flex-wrap gap-2"><button v-for="type in typeNames" :key="type" class="rounded-lg border px-2.5 py-1.5 text-xs" :class="editingRelation.subjectTypes.includes(type)?'border-[var(--accent)] bg-[var(--accent)]/10 text-[var(--accent)]':''" @click="toggleType(editingRelation.subjectTypes,type)">{{ type }}</button></div></div><div><strong class="text-xs">指向哪些类型</strong><div class="mt-2 flex flex-wrap gap-2"><button v-for="type in typeNames" :key="type" class="rounded-lg border px-2.5 py-1.5 text-xs" :class="editingRelation.objectTypes.includes(type)?'border-[var(--accent)] bg-[var(--accent)]/10 text-[var(--accent)]':''" @click="toggleType(editingRelation.objectTypes,type)">{{ type }}</button></div></div></div><label class="mt-4 flex items-center gap-2 text-xs"><input v-model="editingRelation.allowAiCreate" type="checkbox"/>允许 AI 自动识别此关系</label><div class="mt-5 flex justify-end gap-2"><button class="rounded-lg border px-3 py-2 text-sm" @click="editingRelation=null">取消</button><button class="rounded-lg bg-[var(--accent)] px-4 py-2 text-sm text-white" @click="saveRelation">保存</button></div></div></div>
</template>
